// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjdzrxfriezvfxjacche.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqZHpyeGZyaWV6dmZ4amFjY2hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4ODIyMjcsImV4cCI6MjA2MDQ1ODIyN30.gx3n1fKedtU4s4OqKIqPWvUlBQzajOz80rJit1STFwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);